import os

base = "/Users/macbook/Desktop/multi-tenant-sass"

files = {}

files[f"{base}/src/Modules/Employee/HrSaas.Modules.Employee/Infrastructure/Persistence/EmployeeDbContext.cs"] = (
    "using HrSaas.TenantSdk;\n"
    "using MediatR;\n"
    "using Microsoft.EntityFrameworkCore;\n"
    "\n"
    "namespace HrSaas.Modules.Employee.Infrastructure.Persistence;\n"
    "\n"
    "public sealed class EmployeeDbContext(\n"
    "    DbContextOptions<EmployeeDbContext> options,\n"
    "    TenantContext tenantContext,\n"
    "    IPublisher publisher)\n"
    "    : DbContext(options), IEmployeeDbContext\n"
    "{\n"
    "    public DbSet<Domain.Entities.Employee> Employees => Set<Domain.Entities.Employee>();\n"
    "\n"
    "    protected override void OnModelCreating(ModelBuilder modelBuilder)\n"
    "    {\n"
    "        base.OnModelCreating(modelBuilder);\n"
    "        modelBuilder.HasDefaultSchema(\"employee\");\n"
    "        modelBuilder.ApplyConfigurationsFromAssembly(typeof(EmployeeDbContext).Assembly);\n"
    "        modelBuilder.Entity<Domain.Entities.Employee>()\n"
    "            .HasQueryFilter(e => e.TenantId == tenantContext.TenantId && !e.IsDeleted);\n"
    "    }\n"
    "\n"
    "    public override async Task<int> SaveChangesAsync(CancellationToken ct = default)\n"
    "    {\n"
    "        var result = await base.SaveChangesAsync(ct).ConfigureAwait(false);\n"
    "        await DispatchDomainEventsAsync(ct).ConfigureAwait(false);\n"
    "        return result;\n"
    "    }\n"
    "\n"
    "    private async Task DispatchDomainEventsAsync(CancellationToken ct)\n"
    "    {\n"
    "        var entities = ChangeTracker\n"
    "            .Entries<SharedKernel.Entities.BaseEntity>()\n"
    "            .Where(e => e.Entity.DomainEvents.Count > 0)\n"
    "            .Select(e => e.Entity)\n"
    "            .ToList();\n"
    "\n"
    "        var events = entities.SelectMany(e => e.DomainEvents).ToList();\n"
    "        entities.ForEach(e => e.ClearDomainEvents());\n"
    "\n"
    "        foreach (var domainEvent in events)\n"
    "        {\n"
    "            await publisher.Publish(domainEvent, ct).ConfigureAwait(false);\n"
    "        }\n"
    "    }\n"
    "}\n"
)

files[f"{base}/src/Modules/Employee/HrSaas.Modules.Employee/Infrastructure/Persistence/Configurations/EmployeeConfiguration.cs"] = (
    "using Microsoft.EntityFrameworkCore;\n"
    "using Microsoft.EntityFrameworkCore.Metadata.Builders;\n"
    "\n"
    "namespace HrSaas.Modules.Employee.Infrastructure.Persistence.Configurations;\n"
    "\n"
    "public sealed class EmployeeConfiguration : IEntityTypeConfiguration<Domain.Entities.Employee>\n"
    "{\n"
    "    public void Configure(EntityTypeBuilder<Domain.Entities.Employee> builder)\n"
    "    {\n"
    "        builder.ToTable(\"employees\", \"employee\");\n"
    "\n"
    "        builder.HasKey(e => e.Id);\n"
    "\n"
    "        builder.Property(e => e.Id)\n"
    "            .ValueGeneratedNever();\n"
    "\n"
    "        builder.Property(e => e.TenantId)\n"
    "            .IsRequired();\n"
    "\n"
    "        builder.Property(e => e.Name)\n"
    "            .HasMaxLength(200)\n"
    "            .IsRequired();\n"
    "\n"
    "        builder.Property(e => e.Email)\n"
    "            .HasMaxLength(320)\n"
    "            .IsRequired();\n"
    "\n"
    "        builder.Property(e => e.UserId);\n"
    "\n"
    "        builder.Property(e => e.IsActive)\n"
    "            .IsRequired()\n"
    "            .HasDefaultValue(true);\n"
    "\n"
    "        builder.Property(e => e.CreatedAt)\n"
    "            .IsRequired();\n"
    "\n"
    "        builder.Property(e => e.UpdatedAt);\n"
    "\n"
    "        builder.Property(e => e.IsDeleted)\n"
    "            .IsRequired()\n"
    "            .HasDefaultValue(false);\n"
    "\n"
    "        builder.OwnsOne(e => e.Department, dept =>\n"
    "        {\n"
    "            dept.Property(d => d.Name)\n"
    "                .HasColumnName(\"department\")\n"
    "                .HasMaxLength(100)\n"
    "                .IsRequired();\n"
    "        });\n"
    "\n"
    "        builder.OwnsOne(e => e.Position, pos =>\n"
    "        {\n"
    "            pos.Property(p => p.Title)\n"
    "                .HasColumnName(\"position\")\n"
    "                .HasMaxLength(100)\n"
    "                .IsRequired();\n"
    "        });\n"
    "\n"
    "        builder.HasIndex(e => e.TenantId)\n"
    "            .HasDatabaseName(\"idx_employees_tenant_id\");\n"
    "\n"
    "        builder.HasIndex(e => new { e.TenantId, e.Email })\n"
    "            .IsUnique()\n"
    "            .HasDatabaseName(\"idx_employees_tenant_email_unique\");\n"
    "\n"
    "        builder.Ignore(e => e.DomainEvents);\n"
    "    }\n"
    "}\n"
)

files[f"{base}/src/Api/HrSaas.Api/Middleware/ExceptionMiddleware.cs"] = (
    "using FluentValidation;\n"
    "using HrSaas.SharedKernel.Exceptions;\n"
    "using Microsoft.AspNetCore.Mvc;\n"
    "using System.Net;\n"
    "\n"
    "namespace HrSaas.Api.Middleware;\n"
    "\n"
    "public sealed class ExceptionMiddleware(RequestDelegate next, ILogger<ExceptionMiddleware> logger)\n"
    "{\n"
    "    public async Task InvokeAsync(HttpContext context)\n"
    "    {\n"
    "        try\n"
    "        {\n"
    "            await next(context).ConfigureAwait(false);\n"
    "        }\n"
    "        catch (ValidationException ex)\n"
    "        {\n"
    "            logger.LogWarning(\"Validation failed: {Errors}\", ex.Errors);\n"
    "            await WriteProblemDetailsAsync(context, HttpStatusCode.UnprocessableEntity, \"Validation Failed\",\n"
    "                ex.Errors.Select(e => e.ErrorMessage).ToArray()).ConfigureAwait(false);\n"
    "        }\n"
    "        catch (DomainException ex)\n"
    "        {\n"
    "            logger.LogWarning(\"Domain rule violation: {Message}\", ex.Message);\n"
    "            await WriteProblemDetailsAsync(context, HttpStatusCode.BadRequest, \"Domain Rule Violation\", ex.Message).ConfigureAwait(false);\n"
    "        }\n"
    "        catch (TenantNotFoundException ex)\n"
    "        {\n"
    "            logger.LogWarning(\"Tenant not found: {Message}\", ex.Message);\n"
    "            await WriteProblemDetailsAsync(context, HttpStatusCode.Unauthorized, \"Tenant Identification Required\", ex.Message).ConfigureAwait(false);\n"
    "        }\n"
    "        catch (TenantAccessDeniedException ex)\n"
    "        {\n"
    "            logger.LogWarning(\"Tenant access denied: {Message}\", ex.Message);\n"
    "            await WriteProblemDetailsAsync(context, HttpStatusCode.Forbidden, \"Access Denied\", ex.Message).ConfigureAwait(false);\n"
    "        }\n"
    "        catch (NotFoundException ex)\n"
    "        {\n"
    "            await WriteProblemDetailsAsync(context, HttpStatusCode.NotFound, \"Not Found\", ex.Message).ConfigureAwait(false);\n"
    "        }\n"
    "        catch (Exception ex)\n"
    "        {\n"
    "            logger.LogError(ex, \"Unhandled exception\");\n"
    "            await WriteProblemDetailsAsync(context, HttpStatusCode.InternalServerError, \"Internal Server Error\",\n"
    "                \"An unexpected error occurred.\").ConfigureAwait(false);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    private static async Task WriteProblemDetailsAsync(\n"
    "        HttpContext context,\n"
    "        HttpStatusCode statusCode,\n"
    "        string title,\n"
    "        params string[] errors)\n"
    "    {\n"
    "        var problem = new ProblemDetails\n"
    "        {\n"
    "            Title = title,\n"
    "            Status = (int)statusCode,\n"
    "            Instance = context.Request.Path\n"
    "        };\n"
    "\n"
    "        if (errors.Length > 0)\n"
    "        {\n"
    "            problem.Extensions[\"errors\"] = errors;\n"
    "        }\n"
    "\n"
    "        context.Response.StatusCode = (int)statusCode;\n"
    "        context.Response.ContentType = \"application/problem+json\";\n"
    "        await context.Response.WriteAsJsonAsync(problem).ConfigureAwait(false);\n"
    "    }\n"
    "}\n"
)

for path, content in files.items():
    with open(path, 'w') as f:
        f.write(content)
    print(f"OK: {os.path.basename(path)}")
