#!/usr/bin/env python3
import os

ROOT = "/Users/macbook/Desktop/multi-tenant-sass"

files = {}

files["src/Modules/Identity/HrSaas.Modules.Identity/Application/Commands/AuthCommands.cs"] = (
    "using FluentValidation;\n"
    "using HrSaas.Modules.Identity.Application.DTOs;\n"
    "using HrSaas.Modules.Identity.Application.Interfaces;\n"
    "using HrSaas.Modules.Identity.Domain.Entities;\n"
    "using HrSaas.Modules.Identity.Domain.ValueObjects;\n"
    "using HrSaas.SharedKernel.CQRS;\n"
    "using MediatR;\n\n"
    "namespace HrSaas.Modules.Identity.Application.Commands;\n\n"
    "public sealed record RegisterCommand(\n"
    "    Guid TenantId,\n"
    "    string Email,\n"
    "    string Password,\n"
    "    string Role = \"Employee\") : ICommand<AuthTokenDto>;\n\n"
    "public sealed class RegisterCommandValidator : AbstractValidator<RegisterCommand>\n"
    "{\n"
    "    public RegisterCommandValidator()\n"
    "    {\n"
    "        RuleFor(x => x.TenantId).NotEmpty();\n"
    "        RuleFor(x => x.Email).NotEmpty().EmailAddress().MaximumLength(254);\n"
    "        RuleFor(x => x.Password).NotEmpty().MinimumLength(8).MaximumLength(128);\n"
    "        RuleFor(x => x.Role).NotEmpty().Must(r => AppUser.AllowedRoles.Contains(r))\n"
    "            .WithMessage(\"Role must be one of: Admin, Manager, Employee\");\n"
    "    }\n"
    "}\n\n"
    "public sealed class RegisterCommandHandler(\n"
    "    IUserRepository userRepository,\n"
    "    IPasswordHasher passwordHasher,\n"
    "    IJwtTokenService jwtTokenService) : IRequestHandler<RegisterCommand, Result<AuthTokenDto>>\n"
    "{\n"
    "    public async Task<Result<AuthTokenDto>> Handle(RegisterCommand request, CancellationToken cancellationToken)\n"
    "    {\n"
    "        var existing = await userRepository.GetByEmailAsync(request.TenantId, request.Email, cancellationToken).ConfigureAwait(false);\n"
    "        if (existing is not null)\n"
    "        {\n"
    "            return Result<AuthTokenDto>.Failure(\"A user with this email already exists.\", \"EMAIL_TAKEN\");\n"
    "        }\n\n"
    "        var email = Email.Create(request.Email);\n"
    "        var hash = passwordHasher.Hash(request.Password);\n"
    "        var user = AppUser.Create(request.TenantId, email, HashedPassword.FromHash(hash), request.Role);\n\n"
    "        await userRepository.AddAsync(user, cancellationToken).ConfigureAwait(false);\n"
    "        await userRepository.SaveChangesAsync(cancellationToken).ConfigureAwait(false);\n\n"
    "        var accessToken = jwtTokenService.GenerateAccessToken(user.Id, user.TenantId, user.Email.Value, user.Role);\n"
    "        var refreshToken = jwtTokenService.GenerateRefreshToken();\n\n"
    "        return Result<AuthTokenDto>.Success(new AuthTokenDto(\n"
    "            accessToken,\n"
    "            refreshToken,\n"
    "            DateTime.UtcNow.AddHours(1),\n"
    "            new UserDto(user.Id, user.TenantId, user.Email.Value, user.Role, user.IsActive, user.CreatedAt)));\n"
    "    }\n"
    "}\n\n"
    "public sealed record LoginCommand(Guid TenantId, string Email, string Password) : ICommand<AuthTokenDto>;\n\n"
    "public sealed class LoginCommandValidator : AbstractValidator<LoginCommand>\n"
    "{\n"
    "    public LoginCommandValidator()\n"
    "    {\n"
    "        RuleFor(x => x.TenantId).NotEmpty();\n"
    "        RuleFor(x => x.Email).NotEmpty().EmailAddress();\n"
    "        RuleFor(x => x.Password).NotEmpty();\n"
    "    }\n"
    "}\n\n"
    "public sealed class LoginCommandHandler(\n"
    "    IUserRepository userRepository,\n"
    "    IPasswordHasher passwordHasher,\n"
    "    IJwtTokenService jwtTokenService) : IRequestHandler<LoginCommand, Result<AuthTokenDto>>\n"
    "{\n"
    "    public async Task<Result<AuthTokenDto>> Handle(LoginCommand request, CancellationToken cancellationToken)\n"
    "    {\n"
    "        var user = await userRepository.GetByEmailAsync(request.TenantId, request.Email, cancellationToken).ConfigureAwait(false);\n"
    "        if (user is null || !passwordHasher.Verify(request.Password, user.Password.Value))\n"
    "        {\n"
    "            return Result<AuthTokenDto>.Failure(\"Invalid credentials.\", \"INVALID_CREDENTIALS\");\n"
    "        }\n\n"
    "        if (!user.IsActive)\n"
    "        {\n"
    "            return Result<AuthTokenDto>.Failure(\"Account is deactivated.\", \"ACCOUNT_DEACTIVATED\");\n"
    "        }\n\n"
    "        var accessToken = jwtTokenService.GenerateAccessToken(user.Id, user.TenantId, user.Email.Value, user.Role);\n"
    "        var refreshToken = jwtTokenService.GenerateRefreshToken();\n\n"
    "        return Result<AuthTokenDto>.Success(new AuthTokenDto(\n"
    "            accessToken,\n"
    "            refreshToken,\n"
    "            DateTime.UtcNow.AddHours(1),\n"
    "            new UserDto(user.Id, user.TenantId, user.Email.Value, user.Role, user.IsActive, user.CreatedAt)));\n"
    "    }\n"
    "}\n"
)

files["src/Modules/Identity/HrSaas.Modules.Identity/Application/Queries/IdentityQueries.cs"] = (
    "using HrSaas.Modules.Identity.Application.DTOs;\n"
    "using HrSaas.Modules.Identity.Application.Interfaces;\n"
    "using HrSaas.SharedKernel.CQRS;\n"
    "using HrSaas.SharedKernel.Exceptions;\n"
    "using MediatR;\n\n"
    "namespace HrSaas.Modules.Identity.Application.Queries;\n\n"
    "public sealed record GetUserByIdQuery(Guid TenantId, Guid UserId) : IQuery<UserDto>;\n\n"
    "public sealed class GetUserByIdQueryHandler(\n"
    "    IUserRepository userRepository) : IRequestHandler<GetUserByIdQuery, Result<UserDto>>\n"
    "{\n"
    "    public async Task<Result<UserDto>> Handle(GetUserByIdQuery request, CancellationToken cancellationToken)\n"
    "    {\n"
    "        var user = await userRepository.GetByIdAsync(request.UserId, cancellationToken).ConfigureAwait(false);\n"
    "        if (user is null || user.TenantId != request.TenantId)\n"
    "        {\n"
    "            return Result<UserDto>.Failure(\"User not found.\", \"NOT_FOUND\");\n"
    "        }\n\n"
    "        return Result<UserDto>.Success(new UserDto(user.Id, user.TenantId, user.Email.Value, user.Role, user.IsActive, user.CreatedAt));\n"
    "    }\n"
    "}\n\n"
    "public sealed record GetAllUsersQuery(Guid TenantId) : IQuery<IReadOnlyList<UserDto>>;\n\n"
    "public sealed class GetAllUsersQueryHandler(\n"
    "    IUserRepository userRepository) : IRequestHandler<GetAllUsersQuery, Result<IReadOnlyList<UserDto>>>\n"
    "{\n"
    "    public async Task<Result<IReadOnlyList<UserDto>>> Handle(GetAllUsersQuery request, CancellationToken cancellationToken)\n"
    "    {\n"
    "        var users = await userRepository.GetAllAsync(request.TenantId, cancellationToken).ConfigureAwait(false);\n"
    "        var dtos = users.Select(u => new UserDto(u.Id, u.TenantId, u.Email.Value, u.Role, u.IsActive, u.CreatedAt)).ToList().AsReadOnly();\n"
    "        return Result<IReadOnlyList<UserDto>>.Success(dtos);\n"
    "    }\n"
    "}\n"
)

files["src/Modules/Identity/HrSaas.Modules.Identity/Infrastructure/Persistence/IdentityDbContext.cs"] = (
    "using HrSaas.Modules.Identity.Domain.Entities;\n"
    "using HrSaas.TenantSdk;\n"
    "using Microsoft.EntityFrameworkCore;\n\n"
    "namespace HrSaas.Modules.Identity.Infrastructure.Persistence;\n\n"
    "public sealed class IdentityDbContext(DbContextOptions<IdentityDbContext> options, ITenantService tenantService)\n"
    "    : DbContext(options)\n"
    "{\n"
    "    public DbSet<AppUser> Users => Set<AppUser>();\n\n"
    "    protected override void OnModelCreating(ModelBuilder modelBuilder)\n"
    "    {\n"
    "        modelBuilder.HasDefaultSchema(\"identity\");\n"
    "        modelBuilder.ApplyConfigurationsFromAssembly(typeof(IdentityDbContext).Assembly);\n"
    "        base.OnModelCreating(modelBuilder);\n"
    "    }\n"
    "}\n"
)

files["src/Modules/Identity/HrSaas.Modules.Identity/Infrastructure/Persistence/Configurations/UserConfiguration.cs"] = (
    "using HrSaas.Modules.Identity.Domain.Entities;\n"
    "using HrSaas.Modules.Identity.Domain.ValueObjects;\n"
    "using HrSaas.TenantSdk;\n"
    "using Microsoft.EntityFrameworkCore;\n"
    "using Microsoft.EntityFrameworkCore.Metadata.Builders;\n\n"
    "namespace HrSaas.Modules.Identity.Infrastructure.Persistence.Configurations;\n\n"
    "public sealed class UserConfiguration : IEntityTypeConfiguration<AppUser>\n"
    "{\n"
    "    public void Configure(EntityTypeBuilder<AppUser> builder)\n"
    "    {\n"
    "        builder.ToTable(\"users\");\n"
    "        builder.HasKey(u => u.Id);\n"
    "        builder.Property(u => u.Id).ValueGeneratedNever();\n"
    "        builder.Property(u => u.TenantId).IsRequired();\n"
    "        builder.OwnsOne(u => u.Email, e => {\n"
    "            e.Property(x => x.Value).HasColumnName(\"email\").HasMaxLength(254).IsRequired();\n"
    "        });\n"
    "        builder.OwnsOne(u => u.Password, p => {\n"
    "            p.Property(x => x.Value).HasColumnName(\"password_hash\").HasMaxLength(512).IsRequired();\n"
    "        });\n"
    "        builder.Property(u => u.Role).HasMaxLength(32).IsRequired();\n"
    "        builder.Property(u => u.IsActive).IsRequired();\n"
    "        builder.Property(u => u.CreatedAt).IsRequired();\n"
    "        builder.Property(u => u.UpdatedAt);\n"
    "        builder.HasIndex(u => new { u.TenantId, u.Id }).IsUnique();\n"
    "        builder.HasIndex(\"TenantId\", \"email\").IsUnique();\n"
    "    }\n"
    "}\n"
)

files["src/Modules/Identity/HrSaas.Modules.Identity/Infrastructure/Persistence/Repositories/UserRepository.cs"] = (
    "using HrSaas.Modules.Identity.Application.Interfaces;\n"
    "using HrSaas.Modules.Identity.Domain.Entities;\n"
    "using Microsoft.EntityFrameworkCore;\n\n"
    "namespace HrSaas.Modules.Identity.Infrastructure.Persistence.Repositories;\n\n"
    "public sealed class UserRepository(IdentityDbContext dbContext) : IUserRepository\n"
    "{\n"
    "    public async Task<AppUser?> GetByIdAsync(Guid id, CancellationToken ct = default) =>\n"
    "        await dbContext.Users.FirstOrDefaultAsync(u => u.Id == id, ct).ConfigureAwait(false);\n\n"
    "    public async Task<AppUser?> GetByEmailAsync(Guid tenantId, string email, CancellationToken ct = default) =>\n"
    "        await dbContext.Users.FirstOrDefaultAsync(u => u.TenantId == tenantId && u.Email.Value == email.ToLowerInvariant(), ct).ConfigureAwait(false);\n\n"
    "    public async Task<IReadOnlyList<AppUser>> GetAllAsync(Guid tenantId, CancellationToken ct = default) =>\n"
    "        await dbContext.Users.Where(u => u.TenantId == tenantId && !u.IsDeleted).ToListAsync(ct).ConfigureAwait(false);\n\n"
    "    public async Task AddAsync(AppUser user, CancellationToken ct = default) =>\n"
    "        await dbContext.Users.AddAsync(user, ct).ConfigureAwait(false);\n\n"
    "    public void Update(AppUser user) => dbContext.Users.Update(user);\n\n"
    "    public async Task<int> SaveChangesAsync(CancellationToken ct = default) =>\n"
    "        await dbContext.SaveChangesAsync(ct).ConfigureAwait(false);\n"
    "}\n"
)

files["src/Modules/Identity/HrSaas.Modules.Identity/Infrastructure/Services/PasswordHasher.cs"] = (
    "using HrSaas.Modules.Identity.Application.Interfaces;\n\n"
    "namespace HrSaas.Modules.Identity.Infrastructure.Services;\n\n"
    "public sealed class BcryptPasswordHasher : IPasswordHasher\n"
    "{\n"
    "    private const int WorkFactor = 12;\n\n"
    "    public string Hash(string plainText) => BCrypt.Net.BCrypt.HashPassword(plainText, WorkFactor);\n\n"
    "    public bool Verify(string plainText, string hash) => BCrypt.Net.BCrypt.Verify(plainText, hash);\n"
    "}\n"
)

files["src/Modules/Identity/HrSaas.Modules.Identity/IdentityModule.cs"] = (
    "using FluentValidation;\n"
    "using HrSaas.Modules.Identity.Application.Interfaces;\n"
    "using HrSaas.Modules.Identity.Infrastructure.Persistence;\n"
    "using HrSaas.Modules.Identity.Infrastructure.Persistence.Repositories;\n"
    "using HrSaas.Modules.Identity.Infrastructure.Services;\n"
    "using MediatR;\n"
    "using Microsoft.EntityFrameworkCore;\n"
    "using Microsoft.Extensions.Configuration;\n"
    "using Microsoft.Extensions.DependencyInjection;\n\n"
    "namespace HrSaas.Modules.Identity;\n\n"
    "public static class IdentityModule\n"
    "{\n"
    "    public static IServiceCollection AddIdentityModule(this IServiceCollection services, IConfiguration configuration)\n"
    "    {\n"
    "        services.AddDbContext<IdentityDbContext>(opts =>\n"
    "            opts.UseNpgsql(configuration.GetConnectionString(\"DefaultConnection\")));\n\n"
    "        services.AddScoped<IUserRepository, UserRepository>();\n"
    "        services.AddScoped<IPasswordHasher, BcryptPasswordHasher>();\n"
    "        services.AddScoped<IJwtTokenService, JwtTokenService>();\n\n"
    "        services.AddMediatR(cfg => cfg.RegisterServicesFromAssembly(typeof(IdentityModule).Assembly));\n"
    "        services.AddValidatorsFromAssembly(typeof(IdentityModule).Assembly);\n\n"
    "        return services;\n"
    "    }\n"
    "}\n"
)

for rel_path, content in files.items():
    full_path = os.path.join(ROOT, rel_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"wrote {rel_path}")

print("Identity module done")
